ziglang/vscode-zig

.gitignore
.vscode/settings.json
.vscode/tasks.json
package.json
src/extension.ts
src/zigCompilerProvider.ts
tsconfig.json

It's not really feature complete but it is something to build on.
Known issues to deal with:
- Underline entire error instead of only first char
- Check files without generating output files (We probably need a `zig check` or `zig build-lib -o "temp_path/to/output"` for this to work)

Added basic linting functionality

---

src/zigUtil.ts

The code was checking  `elm-package.json` to signal the root of the root
of the project, for zig `build.zig file` is used instead.
Also this doesn't require to iterate over directories, uses simple
recursion instead.
I am using the latest zig version which ships with fmt command. When  `zig fmt` is run the binary will generate `zig-cache` so was running into weird errors because of the binary trying to create the cache on weird places. This fixes that issue because the command will properly use the `zig-cache` already on the project root or creating one in the correct location.

fix using zig fmt from zig v0.4.0

---

.vscodeignore

Originally only wanted to remove 'out/' from the ignore list due to vsce not including it when running `vsce package`, but after seeing 
[https://github.com/Microsoft/vscode/issues/62687](https://github.com/Microsoft/vscode/issues/62687)
and 
[https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/vscodeignore](https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/vscodeignore)
it seemed reasonable to use the template .vscodeignore to cut down on unnecessary files in the final package.

Modifying .vscodeignore to the suggested settings.

---

README.md
package-lock.json
package.json
src/zigFormat.ts

Hello,
Here is the original post:
```
Since zig fmt is the defacto formatter currently, I thought it would make sense to simplify the settings by just requiring that the user sets the path to the zig binary if it's not already in the users path.
This should make it so that it works by default after installing Zig and vscode-zig, while also letting the Zig core team and others choose a custom zig binary (while developing, or other purposes) if needed.
If I missed a use case, please let me know.
```
Creating a new merge request in order to keep the history clean, as I messed up on some of the commits of the previous pull request.
I've included the fixes that were suggested in the previous pull request, too. Please let me know of any additional changes I should include.

Simplifying formatting settings. (second attempt)

---

src/zigFormat.ts

This replaces <stdtin> with actual filename allowing CTRL+click to go to
the offending  position.

add filename to the result of zig fmt failure

---

src/zigFormat.ts

When `zig fmt` returns an error, the extension shows the error in a console window. When the console window appears, it previously stole focus from the editor. Since the extension runs `zig fmt` on save, this was very annoying, since focusing loses your position in the editor and requires you to click back.
This PR makes the extension pass `true` as the `preserveFocus: boolean` parameter to `OutputChannel.show`, which means that the output window doesn't steal focus and your cursor remains in the editor window to fix the typo.

Preserve editor focus when showing error from zig fmt

---

src/zigCompilerProvider.ts

on windows the extension was was looking for nonexistent files because the regex introduced a stray space into paths.

improved regex for scraping compilation errors

---

syntaxes/zig.tmLanguage.json

See https://github.com/ziglang/zig/issues/2129

Update pattern for unicode escape to \u{N...}

---

src/zigFormat.ts

sets the eol to LF instead of CRLF after a format

fix eol on format

---

package.json
src/zigFormat.ts

Hello!
I usually got the errors from vscode's terminal window, so auto revealing output channel was quite annoying. 
This PR fixes this case for me and I hope did not break anything :)

Option to disable automatic raising of output window on formatting problems.

---

src/zigCompilerProvider.ts

fixes issues with how vscode was parsing windows paths into uri's. also changes zig's error notes into info entries rather than warnings, as zig has no warnings.

trim paths to fix issue with uri's

---

src/zigBuild.ts
src/zigCompilerProvider.ts

It wasn't showing errors when there were multiple folders at the root. Now it does.

Fix multi-workspace diagnostics & build

---

.github/workflows/main.yml
.vscodeignore
package.json
src/zigBuild.ts
src/zigCompilerProvider.ts
src/zigFormat.ts
tsconfig.json

Add support for instant diagnostics via `zig astgen`
https://user-images.githubusercontent.com/709451/119241831-44044980-bb0e-11eb-918d-cdb6b9a17932.mov
Plus:
- Fix cursor jumping to end of file on zig fmt in large files
- Fix diagnostics for build on save
- Fix diagnostics for zig build
- Makes diagnostic tokens wrap to end of nearest word instead of single character. It makes it much clearer where errors are located (that's VSCode's behavior when you pass `Infinity` to a column range)
This also:
- Bumps to latest typescript version
- Makes tsconfig.json emit modern JS instead of JS from 2016. VSCode extensions don't need to support Internet Explorer 11 :)
- Bumps to latest VSCode engine version. This is necessary for diagnostics to work.
- Switches to esbuild because `tsc` doesn't seem …

Zig AstGen Diagnostics + more fixes

---

README.md

src/extensions.js does not exist from a clean installation. Running tsc src/extension.ts writes a src/extension.js file (notice no 's' in extension).

Update tsc line to generate .vsix file

---

syntaxes/zig.tmLanguage.json

Adds `anyopaque` keyword, removes `c_void`, and adds a check for parentheses following enum literals, which would indicate that it is actually a function call.

Enum Literals can't be function calls & anyopaque

---

package.json

Change the Git URL in package.json to reference the `ziglang` GitHub org rather than the `zig-lang` GitHub org.
It looks like a typo, or it was hosted at a different org in the past.
Super minor, maybe has no impact, just noticed it when exploring the zig landscape.

Fix Git URL in package.json

---

package.json
syntaxes/codeblock.json

| **Before** | **After** |
| :-- | :-- |
| ![](https://user-images.githubusercontent.com/8186898/180288689-e2fd7a35-c84f-4b7b-8901-a665d18e4514.png) | ![](https://user-images.githubusercontent.com/8186898/180288751-1b3974fc-adf6-4634-a81b-24b638b55a60.png) |

Add syntax highlighting for markdown fenced code block

---

CHANGELOG.md
package-lock.json
package.json
src/zls.ts

This requires a new patch version be released, thus the version bump and changelog entry.

Add aarch64 linux zls builds to extension

---

package.json
syntaxes/zig.tmLanguage.json

This will provide syntax highlighting for `.zon` files.

add `.zon` to associated file extensions

---

CHANGELOG.md
src/zls.ts

On macOS, `zls` is sometimes unable to restart after having been updated  using the command "Zig Language Server: Install Server". The fix is create a new executable file, instead of updating the existing executable file in place, the latter causing a code-signing crash if the kernel is caching the signature.

Fix `zls` not restarting after having been updated on macOS

---

README.md

fix the VSCode Marketplace link in the README

---

src/zigSetup.ts

uri.path adds a leading slash on windows when selecting the zig executable. This causes zls to crash, which is most likely the crash reported in #115.
It's very likely that more uri.path usages are wrong and should become uri.fsPath. 
Relevant API documentation: https://code.visualstudio.com/api/references/vscode-api#Uri

fix specify path adds leading slash on windows

---

CHANGELOG.md
package.json
src/zigBuild.ts
src/zigCompilerProvider.ts
src/zigFormat.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

Closes #119
This also makes the options for zls more obvious, but I'm not quite sure how to best handle not finding a Zig executable.

add option to always search for zig in PATH

---

package.json

This will provide IntelliSense and validation in `zls.json` without needing to specifying `$schema`.

add json validation for zls.json

---

src/zls.ts

@MangoDev1 ran into a Windows permission issue, this fix seemed to work.

Delete old zls binary before renaming to avoid Windows permission error

---

.eslintrc.json
package-lock.json
package.json
src/extension.ts
src/zigBuild.ts
src/zigCompilerProvider.ts
src/zigFormat.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

This would allow us improves code quality, consistency and enhances collaboration

Integrate eslint in codebase

---

package.json

Add new zls settings for controlling parameter name and variable declaration hints, added in 
https://github.com/zigtools/zls/pull/1453

add new zls hint settings

---

CHANGELOG.md
package.json
src/extension.ts
src/zigCompilerProvider.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

Closes #82
Closes #86
Closes #106
Closes #144

Rework initial setup and implement installing specific ZLS version

---

package.json

This prevents it from being synced between machines by default, which is undesirable for people who switch between e.g. Windows and Linux.
This change aligns with how vscode-clangd handles its `clangd.path` setting, as an example: https://github.com/clangd/vscode-clangd/blob/eca1e05a39c4e987dca6247d825dfbe92fd5996f/package.json#L97-L102

Make `zig.zls.path` scoped as `machine-overridable`.

---

src/zls.ts

When you get the `Do you want to install ZLS (the Zig Language Server) for Zig version ...` prompt and you press the close button, ZLS still got installed.

don't install ZLS when user closes prompt

---

package.json
src/zls.ts

Use `zig.zls` as the language client ID and rename trace setting accordingly.

---

package.json

* These will be overwritten by the initial setup process anyway.
* This at least ensures that the default value doesn't cause a warning when editing `settings.json`.
* Looking these programs up in `PATH` seems like a sensible default and is consistent with many other extensions.
Closes #157.

Make `zig.path` and `zig.zls.path` default to `""` (look up in `PATH`).

---

package.json
src/zigCompilerProvider.ts
src/zls.ts

The `enable_ast_check_diagnostics` option has been removed which makes the `astCheckProvider` option obsolete.

update ZLS configuration options

---

src/zls.ts

JavaScript is weird lol
This fixes ZLS not starting automatically. `""` as the path means that Zig and/or ZLS will be looked up in PATH as intended, whereas `undefined` is an undesired state. Interestingly, `undefined` should never actually occur as `""` is the default, so this fix technically does nothing. :P
Not sure if `""` to designate looking up by PATH is the best approach, but I'm not sure what the convention is elsewhere.
Closes #176

Fix JS falsy comparison

---

src/zls.ts

getZigPath also get zig path from environment instead of checking the configure. And the install function calls getZigPath, which ensures unity for the two places.

fix: use getZigPath to determine if zls.install is available

---

syntaxes/zig.tmLanguage.json

Added `>`, `<`, `>=` and `<=` to be highlighted as comparison operators.

Added `>`, `<`, `>=` and `<=` to be highlighted as comparison operators.

---

package.json
src/zigSetup.ts

`zig.path` and `zig.zls.path` default to an empty string instead of null when unset so the previous check would skip the initial setup. Unfortunately this makes it impossible to differentiate between an unset path and lookup in $PATH.

fix detection of unset path options

---

package.json
src/zls.ts

This command may let users think that this is where they are supposed to configure ZLS which is not the case when using VS Code.

remove the "Open ZLS Config" command

---

src/zls.ts

Hi :)
ZLS was broken for me after 0.5.4 and I think that I tracked down the bug...
I don't have `zig.zls.path` set so `!zlsConfig.get<string>("path")` (empty string) would evaluate to `true` and the code would return.
However it should be `false` and not return because of the lookup from PATH.
The check was `zlsConfig.get<string>("path") === undefined` before and with that it works again.

Fix ZLS config path condition

---

package.json
src/zls.ts

fixes  #182
One thing I was wondering about was whether to show a warning when a config option is being ignored because it is not recognized by ZLS. Opted to silently ignore it so that switching between Zig and ZLS versions doesn't become annoying.
I added a warning that shows up when adding a config option in `zig.zls.additionalOptions` even though the option is available in the extension:
`settings.json` after selecting "Use zig.zls.enableAutofix instead":

add `zig.zls.additionalOptions`

---

package-lock.json
package.json
src/zigSetup.ts

It turns out, VS Code already has an API to modify environment variables in the integrated terminal. If only it was documented somewhere :disappointed: 
The VS Code version has been bumped to `1.80.0` which is when the `description` field became available.
closes #171
fixes #159 (except that you are not being asked about it)

Add Zig to PATH in integrated terminal

---

package-lock.json
package.json
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

`zig.path` and `zig.zls.path` default to an empty string which makes it impossible to differentiate between an unset value and lookup in PATH.
The following issues will also be resolved:
- initial setup asks about Zig and ZLS even when using lookup in PATH
- initial setup returns early after installing Zig
- `checkInstalled` would error when ZLS is used from PATH

properly differentiate between lookup in PATH and an unset path option

---

package.json
src/extension.ts
src/zigFormat.ts

This feature is no longer necessary since the extension can provide ast-check diagnostics.
closes #191

remove output channel for `zig fmt`

---

src/zigCompilerProvider.ts
src/zigUtil.ts
src/zls.ts

This lets you use most of https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables in all the zig/zls settings, including `${env:ENV_VAR_HERE}` and other things like `${workspaceFolder}`

Allow predefined variables in all configuration options

---

package-lock.json
package.json
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

Allowing the values to be null disables setting the values in the settings UI.

Do not allow `*.path` options to be null

---

package.json

https://github.com/zigtools/zls/issues/338
Instead of https://github.com/ziglang/vscode-zig/pull/205.

Document that `partial` is better than `full` for `zig.zls.semanticTokens`.

---

syntaxes/zig.tmLanguage.json

This change enables highlighting for the following symbols
= ? . , : ;
closes #207

add symbols to syntax highlighting

---

syntaxes/zig.tmLanguage.json

Pretty sure this is the correct place to change, but unfortunately can't test it locally as my npm and node versions are really old

Highlight bitwise not `~` operator

---

package.json

- added `inlayHintsShowStructLiteralFieldType`
- removed `dangerousComptimeExperimentsDoNotEnable`
- removed `recordSession`
- removed `recordSessionPath`
- removed `replaySessionPath`
- removed `buildRunnerGlobalCachePath`
- removed `completionsWithReplace`

sync ZLS options

---

package.json
src/extension.ts
src/zigFormat.ts
src/zls.ts

Over time, I've see users report issues with code formatting provided by this extension. 
Unfortunately, I have not been able to reproduce any of these issues. They may just be caused by the fact that `zig fmt` is JIT compiled or something unrelated to that.
These changes should (hopefully) make code formatting more reliable by applying the following changes:
- compile `zig fmt` when starting the extension
- make the code formatting provider async and cancel-able
I also changed the default formatting provider from `extension` to `zls`. I've made sure that formatting can fallback to the extension provider if ZLS is not running. Perhaps this makes the `formattingProvider` unnecessary all together but I will leave that to another time.

improve formatting integration

---

package.json

The glob pattern `*/build.zig` means that the extension gets activated iff a subfolder contains a `build.zig`. Obviously we want to look in the root folder so the pattern `build.zig` should be used.

fix activation event when the workspace contains a build.zig

---

src/zigCompilerProvider.ts

When disabling ZLS so that `zig ast-check` diagnostics are provided by the extension itself, the diagnostics are never removed when the file has not errors. The last errors will also remain.

clear ast-check diagnostics when no errors are reported

---

.vscodeignore
package-lock.json
package.json
src/extension.ts
src/minisign.ts
src/versionManager.ts
src/zigDiagnosticsProvider.ts
src/zigFormat.ts
src/zigMainCodeLens.ts
src/zigProvider.ts
src/zigSetup.ts
src/zigTestRunnerProvider.ts
src/zigUtil.ts
src/zls.ts

Installing Zig or ZLS with the extension doesn't properly handle switching between different Zig project. 
You have to manually figure out which version to get and install it every time your switch to a project that requires a different Zig version. Same goes for ZLS. The vscode configuration for Zig also can't handle switching between devices (see #111)
Let's stop giving developer the ability to misconfigure their editor.
1. No initial setup for Zig
2. initial setup for ZLS is only 'yes' or 'no'
3. Done!
This is how the extension selects which version of Zig to install:
- set the `zig.version` config option (can be global or per-workspace)
- manually set the version through the 'Select and Install' popup (per-workspace)
- set `minimum_zig_version` in the `build.zig` of your workspace
- …

introduce a fully featured version manager

---

src/zigSetup.ts

This fixes a bug where zig would not be found in the integrated terminal if the `zig.path` config option has been set. This only happens if the environment variable collection has never been set before in the workspace or if the value is outdated. opening a new workspace is the easiest way to reproduce the issue without modifying the code.

update environment variable collection when the zig.path option is set

---

src/zigProvider.ts
src/zigSetup.ts

See the individual commit messages.
fixes #237

fix some issues when trying to manually set the path to Zig

---

src/zls.ts

The extension would send config options with the value`""` instead of `null` for options like `zig_exe_path` or `global_cache_path`. I also implemented a fix in [ZLS](https://github.com/zigtools/zls/commit/6c6923d7b1c4984554dade667f664d21f42b2b6c)

don't send empty string configs to ZLS where null would be expected

---

src/zigTestRunnerProvider.ts

A while ago I noticed that ZLS started to open files even though I didn't open them myself. I didn't think much of it until I checked out the Zig compiler codebase today and saw ZLS endlessly loading files. The project currently contains 2929 .zig files. The cause has been the ZigTestRunnerProvider which is trying to open every zig file to search for tests. 
Identifying the tests of a workspace is not easily done correctly but this is just asking the extension to self destruct.

don't open every zig file in the workspace just to look for tests

---

src/zls.ts

What a silly mistake by me
fixes  #256

fix configuration middleware for non string config options

---

README.md
package.json
src/zls.ts

I have made a similar [change](https://github.com/zigtools/zls/commit/33f5f98c85790a49a49ca1e33170a9642146c31b) to ZLS in the past with the following rationale:
> This is made to avoid ZLS being called "the Zig Language Server" (or "the LSP") which implies ZLS being "official" / developed by the ZSF.
> Obviously, ZLS still remains a acronym for "Zig Language Server".

refer to ZLS as "ZLS language server" instead of "Zig Language Server"

---

src/zigProvider.ts

The active Zig executable would previously not be updated when changing the `zig.path` config option.
Regression introduced in adef1d3033644422dfe7059b46c8ab2b9fea2a66.

fix zigProvider when modifying zig.path config option

---

src/zigSetup.ts

show a warning if the minimum_zig_version of the project is unsatisfied

---

src/zigSetup.ts
src/zls.ts

I recently noticed this happening more frequently because of the added file watching on `.zigversion` and `build.zig.zon` files. This is relatively easy to reproduce by using version control to simultaneously change both files. The result is the following:

prevent cases where ZLS is started multiple times

---

src/zigMainCodeLens.ts

I'm sorry, my code style is not good.
PowerShell needs to use the call operator (&) when running the zig command.

support powershell call operator

---

package.json

See https://github.com/zigtools/zls/commit/c0e69f7633281126c80bc158c0393c901bb6efce
I also updated the description of `zig.buildOnSave` to warn against usage with `zig.zls.enable_build_on_save`. Related discussion in https://github.com/ziglang/vscode-zig/issues/261.

update descriptions of config options

---

src/extension.ts
src/versionManager.ts
src/zigSetup.ts
src/zls.ts

The VS Code documentation says that the deactivate function can be async but it doesn't seem to work.
The sorting was also wrong.

fix the remove unused installations cleanup

---

src/zigSetup.ts

This PR applies three changes to the version manager. The changes correspond the first three commits.
fixes #247
Using the "Select and Install" popup to switch to a different Zig version will no longer be saved permanently. It will revert to the previous version after restarting VS Code. To make the change permanent, the version should be saved in a `.zigversion`, `build.zig.zon` or `settings.json` file. The extension will automatically suggest this change with a message. If not workspace config has been found, a `.zigversion` file will be created.
I am open to any better wording suggestions for the message. This is what I went for:
If the workspace specified no Zig version, the extension would automatically install the latest tagged release. This commit will try to lookup Zig in the …

various version manager improvements

---

src/zls.ts

This will prevent config options set in the zls.json from being overridden with default values by the extension.
VS Code, in their infinite wisdom, has chosen to default boolean config options to false and string options to an empty string (""), ensuring that null or undefined are never returned.
See zigtools/zls#2135

don't send default config values to ZLS

---

src/zigProvider.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

When an exception occurs because it is updating a read-only settings.json to remove the outdated `initialSetupDone` config option, the extensions fails to initialize properly.
See #392

guard against exceptions when updating configuration

---

src/zls.ts

fixes the regression introduced in https://github.com/ziglang/vscode-zig/pull/393

fix `zig.zls.semanticTokens` not being overridden

---

.github/workflows/main.yml
package.json
src/zigMainCodeLens.ts
src/zls.ts

The CI would previously run `prettier --write . --check` but it should be doing `prettier --check .`

ensure that CI will fail if the code is not properly formatted

---

src/zigProvider.ts
src/zigSetup.ts

The ZigProvider does not update the zig version when the `zig.path` has been removed because it isn't aware of the version managment system. To resolve this, the logic is moved into zigSetup.ts.
Also includes a commit that avoids unnecessarily triggering zig provider on change events.

install Zig if the `zig.path` config option has been unset

---

package-lock.json
package.json
src/versionManager.ts
src/zigSetup.ts
src/zls.ts

This reduces the size of `extension.js` from 1.31MiB to 1.1MiB. I tried to test whether this affects proxy support (https://github.com/ziglang/vscode-zig/issues/388) but I couldn't reproduce the issue.

replace axios with Fetch API

---

package.json
src/zigTestRunnerProvider.ts

[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://lu.ma/open-source-saturday-torino)
Hi! This PR introduces the ability to run a single test through the Code Lens button leveraging the build.zig file, if present. If not, it will fallback to the previous mechanism.
The reason for this is leveraging the full configuration encoded in the build script, as opposed run on a specific file, which could not work under certain conditions such as importing a file from outside the current module (eg: https://github.com/omissis/zig-langchain/blob/main/src/openai/OpenAI.zig#L2).
By running through `zig build test --summary all -- TESTNAME`, such test can be run in isolation during development, allowing for a tight feedback loop.
This …

feat: run test through filtered 'zig build test' instead of 'zig test' if build.zig is present.

---

src/zigProvider.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

It turns out that the 'which' package has the exact logic that is needed to fix #164. A value that has path separators will not be looked up in the $PATH but will try to resolve file extensions on windows.
I've also noticed that it is possible to input relative paths like `./zig` that would be looked up relative to the cwd of the vs code extension host process. Such values will now be rejected with an error message that suggests `${workspaceFolder}` and `~` as an alternative.
The rest of the changes affect error messages which are further explained in the commit messages.

improve the Zig and ZLS executable lookup

---

src/versionManager.ts

The concurrent installations would operate on the same folder overwriting each other causing signature verification to fail for both.
Closes #425

Prevent versionManager from installing same version of exe concurrently

---

package-lock.json
package.json
src/zls.ts

One notable improvement is the new support for VS Code's [LogOutputChannel](https://github.com/microsoft/vscode-languageserver-node/issues/1116) which greatly improves how the ZLS logs are rendered.
Before:
After:
The new output not only looks better but is also more customizable with the log filter in the top right.

update vscode-languageclient to 10.0.0-next.15

---

src/versionManager.ts
src/zigSetup.ts
src/zls.ts

The first commit is an alternative to #429. The additional commits mostly focus on improve the error handling when something in the version manager has gone wrong.

support installation of newer Zig version with new artifact file name

---

package-lock.json
package.json
src/zigDiagnosticsProvider.ts
src/zigUtil.ts
src/zls.ts

I am currently planning to change how ZLS requests config options using the `workspace/Configuration` request which has led me to identify some issues with the extension's handling of this request. The extension currently assumes that ZLS will request individual config options instead using a [ConfigurationItem](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem) with `section == "zls"` to request all config options as a single JSON object. With these changes, the extension should be able to handle both strategies.
This also has the benefit that it can make supporting config options that are not specified in the `package.json` trivial without the need for `zig.zls.additionalOptions` (#182). I plan to open a follow up issue about …

address various issues with the ZLS config middleware

---

src/versionManager.ts
src/zigSetup.ts
src/zigUtil.ts
src/zls.ts

This should make it possible to fetch ZLS 0.15.0 and later as well as any arm build for Zig where `armv7a` has been renamed to `arm`.

resolve the correct tarball name for ZLS 0.15.0+ and arm

---

package.json
src/zigTestRunnerProvider.ts

This adds the `debugTestArgs` option, which allows users to override the arguments used to build a test binary, similar to `testArgs`. It also changes the working directory to the workspace folder to allow running `zig build`.
Note that using the absolute `binaryPath` variable from `build.zig` is currently cumbersome, as it doesn’t integrate well with the way install paths are just relative directories within the install directory.
Supersedes #445
Closes #443

Add configuration `debugTestArgs`
